version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=kuldeep
      - MONGO_PASSWORD=password
      - SESSION_SCRETE=keykey
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kuldeep
      - MONGO_INITDB_ROOT_PASSWORD=password
